services:
  frontend-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: revoicechat_admin_dashboard
    ports:
      - "${WEB_ADMIN_PORT:-5001}:5001"
    volumes:
      - ./www:/usr/share/nginx/html
    restart: unless-stopped
networks:
  default:
    name: app-network